var frases = [
	"El silencio es el único amigo que jamás traiciona. Confucio",
	"El lenguaje artificioso y la conducta aduladora rara vez acompañan a la virtud. Confucio.",
	"Dios o la verdad, es la síntesis de todo lo bueno, justo y exacto, y los que lleguen a personificarse con estos principios se acercan a Él. - Krumm Heller",
	"Nadie puede hacer el bien en un espacio de su vida, mientras hace daño en otro. La vida es un todo indivisible.-Mahatma Gandhi",
	"He aquí el secreto de la vida eterna: vivir en los otros, con los otros y para los otros. - Krumm Heller.",
	"Huir del temor es sólo acrecentarlo -Krishnamurti",
	"Entristécete no porque los hombres no te conozcan, sino porque tú no conoces a los hombres.-Confucio",
	"Preguntando qué era lo difícil, respondió: Conocerse a sí mismo. Qué era fácil: Dar consejos a los demás. Qué era lo más placentero: El éxito. Qué era lo divino: Lo que no tiene principio ni fin. -Tales de Mileto",
	"Aquél que mira a una mujer que no es su esposa como a una madre; la riqueza que no es suya, como al polvo; y a todos los hombres como a él mismo… es un hombre feliz. Aquél que mira todas estas cosas bajo una luz diferente, es un ciego. -Chanakya.",
	"Ni las victorias de los juegos olímpicos, ni las que se alcanzan en batallas, hacen al hombre feliz. Las únicas que le hacen dichoso son las que consigue sobre sí mismo, Las tentaciones y pruebas son combates. Haz vencido una, dos, muchas veces; combate aún. Si llegas al fin a vencer, serás dichoso toda tu vida, como si hubieras vencido siempre. Epicteto",
	"En cien años no podrá alcanzar el grado de perfección; en cambio en una sola hora, puede descender a lo más bajo. Papini",
	"La virtud, como el arte, se consagra constantemente a lo que es difícil de hacer, y cuanto más dura es la tarea más brillante es el éxito. -Aristóteles.",
	"No son las malas hierbas las que ahogan la buena semilla, sino la negligencia del campesino. -Confucio",
	"Un hombre puede estar en un trono y no tener apego alguno; otro puede estar en harapos y tener mucho apego. -Vivekananda",
	"El agricultor no siembra cualquier semilla; la escoge cuidadosamente, pues por experiencia sabe que la cosecha será de la misma naturaleza de la siembra. El hombre sabio observa las leyes de la vida y vive de acuerdo con ellas. Así pues, siembra en el surco de la vida: procedimientos generosos y beneficiosos para todos que, de acuerdo con la ley, tu cosecha siendo buena, hará tu vida mejor -Amado Nervo",
	"El alma no puede tener secretos sin que la conducta lo revele. -Papini",
	"No es el otro el que constituye un obstáculo a tu libertad. Eres tú mismo. Son las fuerzas en ti existentes que cercan tu conciencia. Ellas son tu verdadero y único enemigo -Hervé, Walkman",
	"Los ríos hondos corren en silencio, los arroyos son ruidosos -Proverbio hindú",
	"El ruido no hace bien, el bien no hace ruido -San Vicente de Paul",
	"El sabio en su actitud para con el mundo no tiene predilecciones ni prejuicios. Está del lado de lo que es correcto. -Confucio",
	"En el mero concepto de una cosa no puede hallarse ningún carácter de su existencia. -Emmanuel Kant",
	"Para reinar con eficacia el reino es preciso, ante todo, poner un buen orden en la familia. Un hombre que no sepa dirigir a su familia, es imposible que sepa dirigir a todo un pueblo. -Confucio.",
	"Recordad, bienaventurados hijos de los hombres, que el propósito de la verdadera ciencia, debe ser aumentar la felicidad y liberar a la raza de toda condición externa que no resulte beneficiosa en la exaltación del hombre a la prístina grandeza de su destino cósmico original. -Saint Germain",
	"No esté tu paz en la boca de los hombres; pues si pensaren de ti bien o mal, no serás por eso hombre diferente. -Tomás de Kempis",
	"El deseo y la felicidad no pueden vivir juntos. -Epicteto.",
	"Dijo Kais a su hijo: No consultes a un hombre preocupado, por buen consejero que sea; ni a un hambriento, por inteligente que parezca; ni a un afligido por más confianza que le tengas. Las preocupaciones, las penas y los dolores turban la mente y traban el entendimiento -Sabiduría Árabe.",
	"Renunciad al deseo de propiedad por las cosas temporales: es el primer paso en el camino de la perfección; por medio de este desligamiento absoluto, es como pueden ser combatidas las pasiones -Eliphas Levi.",
	"Gobierna tu mente, o ella te gobernará a ti - Horacio",
	"Si puedes y conviene hablar, sean cosas que edifiquen. Tomás de Kempis.",
	"En vez de temer a la muerte, deberíamos más bien tratar de despertar a la vida; y a la única muerte que deberíamos huir es: Olvidar la presencia de Dios en nosotros Lao Tsé",
	"La soberbia no es grandeza, sino hinchazón; y lo que está hinchado parece grande, pero no está sano. San Agustín.",
	"Instruir como se debe a la juventud, es formar buenos ciudadanos y padres de familia. Virgilio",
	"Seamos sabios como el silencio, fuertes como el viento, útiles como la luz, hagamos de los labios el incensario de las virtudes. Abdul Baha",
	"El que no desea ser engañado, procure no engañar Platón",
	"Si no eres feliz… el culpable eres tú. Epicteto",
	"No se pueden modelar los hijos conforme a las ideas de los padres. Hay que tomarlos como Dios los da, amarlos y educarlos lo mejor posible, sin torcer su inclinación. Goethe",
	"No hay mayor grandeza que vencerse a sí mismo. Esa es la grandeza… Sócrates",
	"No conozco ningún otro signo de superioridad que la bondad - Beethoven",
	"El entendimiento no puede intuir nada, y los sentidos no pueden pensar nada. Sólo de su unión puede originarse conocimiento. Emmanuel Kant.",
	"Por lo que poco o nada vale, se mira mucho; y por lo que es muy necesario, se pasa con descuido; porque todo hombre se va a lo exterior; y, si presto no vuelve en sí, con gusto se está envuelto en ello Tomás de Kempis.",
	"La mujer es la ley de la belleza y la ley debe ser obedecida y no infringida. La mujer es la religión de la naturaleza cuya moral debe ser sentida y no balbuceada con palabras. Dios es una palabra misteriosa y la mujer es su significado. Mago Jefa",
	"Sólo lo semejante puede ser conocido por lo semejante. Los sentidos nos presentan un mundo cambiante, no verdadero, de sombras. Es el alma la que llega a conocer lo esencial de las cosas, es ella la que conoce el mundo de las ideas. Si lo conoce, es porque participa de él, porque es semejante a ellas. Si es semejante a las ideas, también es, como ella, imperecedera. Fedón",
	"Cuanto el hombre quisiera ser más espiritual, tanto más amarga se le hará la vida; porque conoce mejor y ve más claros los defectos de la corrupción humana Tomás de Kempis",
	"La mujer es el divino arte que no imita, sino explica la divinidad con símbolos. La mujer es la más alta belleza de Dios, el amor la manifiesta, el deseo la mata. La mujer es el pensamiento más hermoso del Absoluto, que debe ser captada por la inteligencia y no vista por los ojos. Mago Jefa",
	"El hombre como cerebro, cual dinamo, fabrica fuerza, la mujer como corazón produce Amor, la fuerza mata, el Amor resucita. Para volver a Dios en clara senda de paz, salvando la febril contienda, es la mujer el único camino. Mago Jefa.",
	"Las experiencias nos muestran tal como somos, nos hacen ver nuestros propios defectos. Goethe",
	"Ya te he dicho, discípulo, que los males del presente son la causa de la ignorancia del pasado y que por lo tanto no tienen remedio. Pero como los males del futuro serán la consecuencia de los males de la ignorancia del presente, tratemos de ser sabios para evitarlos. Sabiduría Hindú",
	"Una vez había un ciervo muy elegante que admiraba sus cuernos y odiaba sus horribles patas. Pero un día llegó un cazador y las horribles patas del ciervo le permitieron correr y salvarse. Más tarde, los hermosos cuernos se le enredaron en la maleza y antes de que pudiera escapar, fue alcanzado por un tiro. Samaniego",
	"La mayor pobreza es la ignorancia. Panchatantra",
	"Si no se obtiene el objeto deseado hay infelicidad. Si se consigue, existe la ansiedad por su posible pérdida. Si falta o su respuesta es negativa, hay mayor desdicha. De este modo, la verdadera dicha consiste en el renunciamiento del deseo. Sivananda",
	"El placer es un enemigo que debe volverse forzosamente nuestro señor o nuestro esclavo; no se disfruta si no se le vence Eliphas Levi",
	"El culpable que se arrepiente, aún no está perdido. Demócrates",
	"El amor es el ala veloz que Dios ha dado al alma para que vuele hasta el cielo. Miguel Ángel",
	"El placer más noble, es el júbilo de comprender. Leonardo Da Vinci",
	"El mejor indicio de la sabiduría es la concordia entre las palabras y las obras… Séneca",
	"Si yo viajase con dos compañeros, uno virtuoso y otro deshonesto, ambos me servirían de maestros. Percibiría lo bueno del primero y le copiaría, en tanto que los defectos que viera en el segundo trataría de corregírmelos. Confucio",
	"Si yo viajase con dos compañeros, uno virtuoso y otro deshonesto, ambos me servirían de maestros. Percibiría lo bueno del primero y le copiaría, en tanto que los defectos que viera en el segundo trataría de corregírmelos. Confucio",
	"La liberación no puede alcanzarse sino por la percepción de la identidad del espíritu individual con el espíritu universal. Lao-Tsé",
	"Oculta tu secreto hasta al amigo más seguro; aprende a callar… Beethoven",
	"Si se os pregunta, ¿Qué es el silencio? Responded: Es la primera piedra del templo de la sabiduría. Pitágoras",
	"No está bien descubrir las faltas sin indicar a la vez el remedio para combatirlas. Goethe.",
	"El mayor error que los médicos cometen es intentar la curación del cuerpo sin intentar la curación del alma; sin embargo, alma y cuerpo son uno y no deberían ser tratados separadamente. Platón",
	"Cuando un hombre se guía por los principios de la reciprocidad y de la conciencia, no se haya muy lejos de la ley moral. Lo que no deseas que otros te hagan a ti, no lo hagas a los demás. Confucio.",
	"El temor, el miedo, el anhelo de seguridad, de protección, llevan al hombre a formar partidos políticos o agrupaciones religiosas, con las cuales se identifica… así las diferencias nacen, los antagonismos se desarrollan y las guerras continúan. Krishnamurti.",
	"Quien no es feliz con poco, no lo será con mucho; quien no aprecia lo pequeño no podrá ser cuidadoso de lo grande; a quien lo suficiente no basta está al margen de la virtud, pues el cuerpo físico vive de un día para otro y si se le proporciona lo que realmente necesita, habrá tiempo todavía para la meditación, mientras que si se trata de darle cuanto desea, la tarea será inacabable. Lao-Tsé",
	"Si tú y yo discutimos y tú vences, ¿Será acaso verdadero lo tuyo y falso lo mío? Lao-Tsé",
	"El hombre más feliz, es el que encuentra paz en su hogar. Goethe",
	"Sabed que cuando uno es amigo de sí mismo, lo es también de todo el mundo. Séneca.",
	"Hay que mostrar mayor rapidez en calmar un resentimiento que en apagar un incendio, porque las consecuencias del primero son infinitamente más peligrosas que los resultados del último; el incendio finaliza abrasando algunas casas a lo más, mientras que el resentimiento puede causar guerras crueles, con la ruina y destrucción total de los pueblos... Heráclito.",
	"Procedemos de Dios. Como el árbol de la raíz y el arroyo del manantial; por eso debemos quedar siempre en comunicación con El, como el tronco a la raíz. Pues el arroyo se seca cuando se lo separa de su manantial y el árbol fenece cuando es arrancado de sus raíces. Pitágoras.",
	"El grado máximo de un medicamento, es el amor Paracelso",
	"¿Acaso de veras se vive con raíz en la tierra?. No para siempre en la Tierra: Solo un poco aquí. Aunque sea de jade se quiebra, aunque sea de oro se rompe, aunque sea de plumaje de Quetzal se desgarra. No para siempre en la tierra: Solo un poco aquí. -Netzahualcoyotl.",
	"Alterivs non sit qvi svvs esse potest, No seas otro si puedes ser tú mismo Teofrasto Paracelso",
	"No eres más santo porque te alaben, ni más vil porque te desprecien. Lo que eres, eso eres; y por más que te estimen los hombres, no puedes ser, ante Dios, más grande de lo que eres. - Tomás de Kempis",
	"Saber que no se sabe, eso es humildad. Pensar que uno sabe lo que no sabe, eso es enfermedad. Lao-tsé",
	"El sabio puede cambiar de opinión. El necio, nunca. Inmanuel Kant",
	"La raza humana se encuentra en la mejor situación cuando posee el más alto grado de libertad. Dante Alighieri",
	"La verdadera sabiduría está en reconocer la propia ignorancia. Sócrates",
	"La mayor sabiduría que existe es conocerse a uno mismo. Galileo Galilei",
	"El hombre más feliz del mundo es aquel que sepa reconocer los méritos de los demás y pueda alegrarse del bien ajeno como si fuera propio - Johann Wolfgang Goethe",
	"Donde reina el amor, sobran las leyes -Platón",
	"No temas a las tinieblas, si llevas la luz dentro de ti. Sivananda",
	"No se nos otorgará la libertad externa más que en la medida exacta en que hayamos sabido, en un momento determinado, desarrollar nuestra libertad interna. -Mahatma Gandhi",
	"No hagas a los otros lo que no te gustaría que te hicieran a ti Confucio",
	"Algunos piensan que conocen a todos, cuando en realidad no se conocen a sí mismos Alberto Durero",
	"¡En verdad os digo: Vale más dar que recibir! -Amado Nervo",
	"Pero ante todo, SED VERÍDICOS. Únicamente la Verdad da a la palabra el Poder de la Lira de Orfeo. -Pitágoras",
	"Ten por sabido, mi querido Critón, que el hablar de una manera impropia es no sólo cometer una falta en lo que se dice, sino una especie de daño que se causa a las Almas. - Platón",
	"Si juzgas a la gente, no tienes tiempo de amarlas - Goethe",
	"No abras los labios si no estas seguro de lo que vas a decir; es más hermoso el Silencio - Proverbio. Árabe",
	"Transporta un puñado de tierra todos los días y construirás una montaña - Confucio",
	"Habitúa tus labios a decir palabras gentiles, tus manos a hacer obras útiles; no te encolerices. - Versos Áureos",
	"Nuestra mayor gloria no está en no caer jamás, sino en levantarnos cada vez que caemos – Confucio",
	"Quien guarda su boca, guarda su Alma -Salomón",
	"Es más importante poner en la oración el propio corazón, que poner palabras de otros sin nada del corazón propio -Mahatma Gandhi.",
	"Si tu grandeza humana despierta tu vanidad, piensa en el Espacio, cuya grandeza es mucho mayor que la tuya, pues contiene todas las cosas. -Tales de Mileto",
	"El temor y la duda son dos ladrones de la felicidad humana. -Saint Germain",
	"La enfermedad es el resultado no sólo de nuestros actos sino también de nuestros pensamientos -Mahatma Ghandi",
	"Debes fundamentar en el Amor la Sabiduría. Platón",
	"El hombre más noble es digno, pero no orgulloso; el inferior es orgulloso pero no es digno. -Confucio",
	"El mejor indicio de la sabiduría es la concordancia entre las palabras y las obras. -Confucio",
	"Cuando el Hombre no se encuentra a sí mismo no encuentra nada -Goethe",
	"Amar la libertad sobre todas las cosas y aún cundo fuera por un trono nunca traicionar la verdad -Beethoven",
	"La incapacidad de aceptar la importancia de la exploración interior ha sido el gran peligro del hombre, de perder su espiritualidad -Emmanuel Kant",
	"No es perezoso solamente el que nada hace, sino también el que estando en sus manos hacer las cosas, no las hace Sócrates",
	"Al hombre, en verdad, solo se le conoce por sus sueños. Platón.",
	"Toda teoría es gris y sólo es verde el árbol de doradas frutas que es la vida -Goethe",
	"No permitas que el dulce sueño se deslice bajo tus ojos antes que hayas, examinado y meditado cada una de las escenas del día -PITÁGORAS",
	"El hombre superior gusta de ser lento en palabras, pero rápido en obras -Confucio",
	"Leer sin meditar es una ocupación inútil. Confucio",
	"Bienaventurado aquel cuyos vicios mueren antes que él. (Hermes Trismegisto).",
	"El principal secreto de la gran Obra, es la capacidad de matar al vivo, Egos y devolver la vida al muerto Ser. (Fulcanelli).",
	"Grave muerte espera a aquel a quien todo el mundo conoce y muere sin conocerse a sí mismo. (Seneca)",
	"EL CONOCIMIENTO otorga la LIBERTAD...-Sri Swami Sivananda",
	"Solo es digno de LIBERTAD aquel que es capaz de conquistarla día a día. —Goethe",
	"Cuando veas a un hombre bueno, trata de imitarlo; cuando veas a un hombre malo, examínate a tí mísmo. - Confucio",
	"Buscando el bien de nuestros semejantes, encontramos el nuestro. Platón",
	"¿Quieres contribuir a hacer un mundo feliz?, Ayuda a tu prójimo a encontrar dentro de sí mismo lo que estima que han perdido: El Amor. - Gohete",
	"El amor y la verdad están tan unidos que es prácticamente imposible separarlos; son como las dos caras de la misma moneda. -MAHATMA GHANDI",
	"La conciencia es el mejor libro de moral, el cual debemos consultar a menudo. Descartes",
	"El yo es insaciable, no hay ningún medio de satisfacerlo. Es como una vasija agujereada, como un pozo sin fondo que no se puede llenar nunca - Krishnamurti.",
	"El maestro aparece cuando el discípulo esta a punto. Fulcanelli",
	"Las fuerzas que se encuentran dentro de nosotros son las que verdaderamente curan las enfermedades. -Hipócrates",
	"Obra como si la máxima de tu voluntad y de tu conducta fuese ha ser declarada código universal para todos los hombres. Emmanuel Kant",
	"Aprender a vencerse es aprender a vivir,-Eliphas Levi",
	"Pobre no es el que tiene poco sino el que mucho desea. Séneca",
	"La no-violencia que nace del fondo de nuestro espíritu se convierte en una verdadera fuerza. Mahatma Ghandhi"
]	
	